---
title: "Initial Post"
description: |
  Propsal for senior project for fall 2021
author: []
date: 09-24-2021
output:
  distill::distill_article:
    self_contained: false
draft: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Personal Background

I took MATH 425 in Fall 2020 and MATH 450 in Winter 2021, but I am registered for MATH 488 this semester. I'm a biostatistics major, but I am more interested in the bioinformatics portion of it. By that I mean I want to help people by finding medicines that works for their biological conditions using the data in their DNA, but I have no concrete plans after graduation yet. My BYUI email is per16018@byui.edu.

### Project Background

Many diseases have genetic markers that make people predisposed to them like asthma, diabetes, thyroid problems, and even skin things like eczema. These are actually all autoimmune diseases that I mentioned, which I spent a semester learning about a couple semesters ago in my bioinformatics class. I know there are some that have similar markers and if you have one illness, you can be more likely to have others. I have a lot of diseases that run in my family including asthma, arthritis, and Hashimoto's thyroiditis. When there are more than one autoimmune diseases found in the same patient, it is called co-occurence and if there are at least 3 autoimmune  diseases, it is called multiple autoimmune syndrome (MAS). I wanted to look at which ones were connected.

### Domain to Investigate

I will need to look at the research that has already been done about related diseases and also research diseases known to have genetic links in the first place. To find data for it, I would need to look at the NCBI database. Reading articles on the subject could also be beneficial. 

### Proposed Deliverables

* Find and clean datasets to use for comparisons
* Learn how to show the graphics for comparing genes and diseases in r
* Use statistical analysis to figure out if the differences are significant
 

Learn more about using Distill at <https://rstudio.github.io/distill>.


